export enum QUERY_KEY {
  user = "user",
  wishlist = "wishlist",
  password = "password",
  products = "products",
  recommendedProducts = "recommendedProducts",
  categoryProducts = "categoryProducts",
  cart = "cart",
  order = "order",
  address = "address",
  settings = "settings",
  support = "support",
  notification = "notification",
  category = "category",
  wallet = "wallet",
  transactions = "transactions",
  banks = "banks",
  commercialBanks = "commercialBanks",
  productReviews = "productReviews",
  trendingProducts = "trendingProducts",
  shops = "shops",
  sizes = "sizes",
  colors = "colors",
  profile = "profile",
  productSearch = "productSearch",
  referralCode = "referralCode",
}
