services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: africanmarkethub-api:latest
        container_name: api-app
        restart: unless-stopped
        working_dir: /var/www
        env_file:
            - .env.docker
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - db

    webserver:
        image: nginx:stable-alpine
        container_name: api-nginx
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: api-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    adminer:
        image: adminer:latest
        container_name: api-adminer
        restart: unless-stopped
        environment:
            - ADMINER_DEFAULT_SERVER=db
        depends_on:
            - db
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
